### ISSUE TITLE
请教个问题

### ISSUE THREAD

**Issue by HppZ** [higankanshi/HLib#2]
http://higan.sinaapp.com/?p=82  你的这篇文章里照片的布局是怎么做的？  我继承了panel作为gridview的itempanel，为什么重写panel的MeasureOverride方法时， size constraint参数的width一直是无穷大？所以效果是一列很长的布局。
谢谢。

**Comment by devkanro** [comment]
你可以看看之前的几篇文章
http://higan.sinaapp.com/?p=45
